[package]
name = "rtracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx-maths = { version = "0.2.8", features = ["swizzle"] }
image = "0.24.5"
